// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package comm.pose;

public final class Pose {
	private Pose() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface MessageOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required .comm.pose.Message.Type type = 2;
		boolean hasType();

		comm.pose.Pose.Message.Type getType();

		// required .comm.pose.Data data = 3;
		boolean hasData();

		comm.pose.Pose.Data getData();

		comm.pose.Pose.DataOrBuilder getDataOrBuilder();
	}

	public static final class Message extends
			com.google.protobuf.GeneratedMessage implements MessageOrBuilder {
		// Use Message.newBuilder() to construct.
		private Message(Builder builder) {
			super(builder);
		}

		private Message(boolean noInit) {
		}

		private static final Message defaultInstance;

		public static Message getDefaultInstance() {
			return defaultInstance;
		}

		public Message getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return comm.pose.Pose.internal_static_comm_pose_Message_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return comm.pose.Pose.internal_static_comm_pose_Message_fieldAccessorTable;
		}

		public enum Type implements com.google.protobuf.ProtocolMessageEnum {
			COMMAND(0, 1), DATA(1, 2), ;

			public static final int COMMAND_VALUE = 1;
			public static final int DATA_VALUE = 2;

			public final int getNumber() {
				return value;
			}

			public static Type valueOf(int value) {
				switch (value) {
				case 1:
					return COMMAND;
				case 2:
					return DATA;
				default:
					return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Type> internalGetValueMap() {
				return internalValueMap;
			}

			private static com.google.protobuf.Internal.EnumLiteMap<Type> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Type>() {
				public Type findValueByNumber(int number) {
					return Type.valueOf(number);
				}
			};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return comm.pose.Pose.Message.getDescriptor().getEnumTypes()
						.get(0);
			}

			private static final Type[] VALUES = { COMMAND, DATA, };

			public static Type valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private Type(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:comm.pose.Message.Type)
		}

		private int bitField0_;
		// required .comm.pose.Message.Type type = 2;
		public static final int TYPE_FIELD_NUMBER = 2;
		private comm.pose.Pose.Message.Type type_;

		public boolean hasType() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public comm.pose.Pose.Message.Type getType() {
			return type_;
		}

		// required .comm.pose.Data data = 3;
		public static final int DATA_FIELD_NUMBER = 3;
		private comm.pose.Pose.Data data_;

		public boolean hasData() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public comm.pose.Pose.Data getData() {
			return data_;
		}

		public comm.pose.Pose.DataOrBuilder getDataOrBuilder() {
			return data_;
		}

		private void initFields() {
			type_ = comm.pose.Pose.Message.Type.COMMAND;
			data_ = comm.pose.Pose.Data.getDefaultInstance();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasData()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!getData().isInitialized()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeEnum(2, type_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeMessage(3, data_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(
						2, type_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(3, data_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static comm.pose.Pose.Message parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static comm.pose.Pose.Message parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.Message parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static comm.pose.Pose.Message parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.Message parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static comm.pose.Pose.Message parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.Message parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static comm.pose.Pose.Message parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static comm.pose.Pose.Message parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static comm.pose.Pose.Message parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(comm.pose.Pose.Message prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				comm.pose.Pose.MessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return comm.pose.Pose.internal_static_comm_pose_Message_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return comm.pose.Pose.internal_static_comm_pose_Message_fieldAccessorTable;
			}

			// Construct using comm.pose.Pose.Message.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getDataFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				type_ = comm.pose.Pose.Message.Type.COMMAND;
				bitField0_ = (bitField0_ & ~0x00000001);
				if (dataBuilder_ == null) {
					data_ = comm.pose.Pose.Data.getDefaultInstance();
				} else {
					dataBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return comm.pose.Pose.Message.getDescriptor();
			}

			public comm.pose.Pose.Message getDefaultInstanceForType() {
				return comm.pose.Pose.Message.getDefaultInstance();
			}

			public comm.pose.Pose.Message build() {
				comm.pose.Pose.Message result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private comm.pose.Pose.Message buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				comm.pose.Pose.Message result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public comm.pose.Pose.Message buildPartial() {
				comm.pose.Pose.Message result = new comm.pose.Pose.Message(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.type_ = type_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				if (dataBuilder_ == null) {
					result.data_ = data_;
				} else {
					result.data_ = dataBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof comm.pose.Pose.Message) {
					return mergeFrom((comm.pose.Pose.Message) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(comm.pose.Pose.Message other) {
				if (other == comm.pose.Pose.Message.getDefaultInstance())
					return this;
				if (other.hasType()) {
					setType(other.getType());
				}
				if (other.hasData()) {
					mergeData(other.getData());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasType()) {

					return false;
				}
				if (!hasData()) {

					return false;
				}
				if (!getData().isInitialized()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 16: {
						int rawValue = input.readEnum();
						comm.pose.Pose.Message.Type value = comm.pose.Pose.Message.Type
								.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(2, rawValue);
						} else {
							bitField0_ |= 0x00000001;
							type_ = value;
						}
						break;
					}
					case 26: {
						comm.pose.Pose.Data.Builder subBuilder = comm.pose.Pose.Data
								.newBuilder();
						if (hasData()) {
							subBuilder.mergeFrom(getData());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setData(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required .comm.pose.Message.Type type = 2;
			private comm.pose.Pose.Message.Type type_ = comm.pose.Pose.Message.Type.COMMAND;

			public boolean hasType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public comm.pose.Pose.Message.Type getType() {
				return type_;
			}

			public Builder setType(comm.pose.Pose.Message.Type value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				type_ = value;
				onChanged();
				return this;
			}

			public Builder clearType() {
				bitField0_ = (bitField0_ & ~0x00000001);
				type_ = comm.pose.Pose.Message.Type.COMMAND;
				onChanged();
				return this;
			}

			// required .comm.pose.Data data = 3;
			private comm.pose.Pose.Data data_ = comm.pose.Pose.Data
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<comm.pose.Pose.Data, comm.pose.Pose.Data.Builder, comm.pose.Pose.DataOrBuilder> dataBuilder_;

			public boolean hasData() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public comm.pose.Pose.Data getData() {
				if (dataBuilder_ == null) {
					return data_;
				} else {
					return dataBuilder_.getMessage();
				}
			}

			public Builder setData(comm.pose.Pose.Data value) {
				if (dataBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					data_ = value;
					onChanged();
				} else {
					dataBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			public Builder setData(comm.pose.Pose.Data.Builder builderForValue) {
				if (dataBuilder_ == null) {
					data_ = builderForValue.build();
					onChanged();
				} else {
					dataBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			public Builder mergeData(comm.pose.Pose.Data value) {
				if (dataBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)
							&& data_ != comm.pose.Pose.Data
									.getDefaultInstance()) {
						data_ = comm.pose.Pose.Data.newBuilder(data_)
								.mergeFrom(value).buildPartial();
					} else {
						data_ = value;
					}
					onChanged();
				} else {
					dataBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			public Builder clearData() {
				if (dataBuilder_ == null) {
					data_ = comm.pose.Pose.Data.getDefaultInstance();
					onChanged();
				} else {
					dataBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public comm.pose.Pose.Data.Builder getDataBuilder() {
				bitField0_ |= 0x00000002;
				onChanged();
				return getDataFieldBuilder().getBuilder();
			}

			public comm.pose.Pose.DataOrBuilder getDataOrBuilder() {
				if (dataBuilder_ != null) {
					return dataBuilder_.getMessageOrBuilder();
				} else {
					return data_;
				}
			}

			private com.google.protobuf.SingleFieldBuilder<comm.pose.Pose.Data, comm.pose.Pose.Data.Builder, comm.pose.Pose.DataOrBuilder> getDataFieldBuilder() {
				if (dataBuilder_ == null) {
					dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<comm.pose.Pose.Data, comm.pose.Pose.Data.Builder, comm.pose.Pose.DataOrBuilder>(
							data_, getParentForChildren(), isClean());
					data_ = null;
				}
				return dataBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:comm.pose.Message)
		}

		static {
			defaultInstance = new Message(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:comm.pose.Message)
	}

	public interface DataOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// optional .comm.pose.Data.Command command = 1;
		boolean hasCommand();

		comm.pose.Pose.Data.Command getCommand();

		// optional .comm.pose.Data.Status status = 2;
		boolean hasStatus();

		comm.pose.Pose.Data.Status getStatus();

		// optional .comm.pose.PoseData pose = 3;
		boolean hasPose();

		comm.pose.Pose.PoseData getPose();

		comm.pose.Pose.PoseDataOrBuilder getPoseOrBuilder();
	}

	public static final class Data extends com.google.protobuf.GeneratedMessage
			implements DataOrBuilder {
		// Use Data.newBuilder() to construct.
		private Data(Builder builder) {
			super(builder);
		}

		private Data(boolean noInit) {
		}

		private static final Data defaultInstance;

		public static Data getDefaultInstance() {
			return defaultInstance;
		}

		public Data getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return comm.pose.Pose.internal_static_comm_pose_Data_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return comm.pose.Pose.internal_static_comm_pose_Data_fieldAccessorTable;
		}

		public enum Command implements com.google.protobuf.ProtocolMessageEnum {
			CARIBRATE(0, 1), SEND_DATA(1, 2), ;

			public static final int CARIBRATE_VALUE = 1;
			public static final int SEND_DATA_VALUE = 2;

			public final int getNumber() {
				return value;
			}

			public static Command valueOf(int value) {
				switch (value) {
				case 1:
					return CARIBRATE;
				case 2:
					return SEND_DATA;
				default:
					return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Command> internalGetValueMap() {
				return internalValueMap;
			}

			private static com.google.protobuf.Internal.EnumLiteMap<Command> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Command>() {
				public Command findValueByNumber(int number) {
					return Command.valueOf(number);
				}
			};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return comm.pose.Pose.Data.getDescriptor().getEnumTypes()
						.get(0);
			}

			private static final Command[] VALUES = { CARIBRATE, SEND_DATA, };

			public static Command valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private Command(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:comm.pose.Data.Command)
		}

		public enum Status implements com.google.protobuf.ProtocolMessageEnum {
			ACK(0, 1), CARIBRATED(1, 2), CAPTURED_POSE(2, 3), ;

			public static final int ACK_VALUE = 1;
			public static final int CARIBRATED_VALUE = 2;
			public static final int CAPTURED_POSE_VALUE = 3;

			public final int getNumber() {
				return value;
			}

			public static Status valueOf(int value) {
				switch (value) {
				case 1:
					return ACK;
				case 2:
					return CARIBRATED;
				case 3:
					return CAPTURED_POSE;
				default:
					return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Status> internalGetValueMap() {
				return internalValueMap;
			}

			private static com.google.protobuf.Internal.EnumLiteMap<Status> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Status>() {
				public Status findValueByNumber(int number) {
					return Status.valueOf(number);
				}
			};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return comm.pose.Pose.Data.getDescriptor().getEnumTypes()
						.get(1);
			}

			private static final Status[] VALUES = { ACK, CARIBRATED,
					CAPTURED_POSE, };

			public static Status valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private Status(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:comm.pose.Data.Status)
		}

		private int bitField0_;
		// optional .comm.pose.Data.Command command = 1;
		public static final int COMMAND_FIELD_NUMBER = 1;
		private comm.pose.Pose.Data.Command command_;

		public boolean hasCommand() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public comm.pose.Pose.Data.Command getCommand() {
			return command_;
		}

		// optional .comm.pose.Data.Status status = 2;
		public static final int STATUS_FIELD_NUMBER = 2;
		private comm.pose.Pose.Data.Status status_;

		public boolean hasStatus() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public comm.pose.Pose.Data.Status getStatus() {
			return status_;
		}

		// optional .comm.pose.PoseData pose = 3;
		public static final int POSE_FIELD_NUMBER = 3;
		private comm.pose.Pose.PoseData pose_;

		public boolean hasPose() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public comm.pose.Pose.PoseData getPose() {
			return pose_;
		}

		public comm.pose.Pose.PoseDataOrBuilder getPoseOrBuilder() {
			return pose_;
		}

		private void initFields() {
			command_ = comm.pose.Pose.Data.Command.CARIBRATE;
			status_ = comm.pose.Pose.Data.Status.ACK;
			pose_ = comm.pose.Pose.PoseData.getDefaultInstance();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (hasPose()) {
				if (!getPose().isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeEnum(1, command_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeEnum(2, status_.getNumber());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeMessage(3, pose_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(
						1, command_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(
						2, status_.getNumber());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(3, pose_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static comm.pose.Pose.Data parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static comm.pose.Pose.Data parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.Data parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static comm.pose.Pose.Data parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.Data parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static comm.pose.Pose.Data parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.Data parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static comm.pose.Pose.Data parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static comm.pose.Pose.Data parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static comm.pose.Pose.Data parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(comm.pose.Pose.Data prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				comm.pose.Pose.DataOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return comm.pose.Pose.internal_static_comm_pose_Data_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return comm.pose.Pose.internal_static_comm_pose_Data_fieldAccessorTable;
			}

			// Construct using comm.pose.Pose.Data.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getPoseFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				command_ = comm.pose.Pose.Data.Command.CARIBRATE;
				bitField0_ = (bitField0_ & ~0x00000001);
				status_ = comm.pose.Pose.Data.Status.ACK;
				bitField0_ = (bitField0_ & ~0x00000002);
				if (poseBuilder_ == null) {
					pose_ = comm.pose.Pose.PoseData.getDefaultInstance();
				} else {
					poseBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return comm.pose.Pose.Data.getDescriptor();
			}

			public comm.pose.Pose.Data getDefaultInstanceForType() {
				return comm.pose.Pose.Data.getDefaultInstance();
			}

			public comm.pose.Pose.Data build() {
				comm.pose.Pose.Data result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private comm.pose.Pose.Data buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				comm.pose.Pose.Data result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public comm.pose.Pose.Data buildPartial() {
				comm.pose.Pose.Data result = new comm.pose.Pose.Data(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.command_ = command_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.status_ = status_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				if (poseBuilder_ == null) {
					result.pose_ = pose_;
				} else {
					result.pose_ = poseBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof comm.pose.Pose.Data) {
					return mergeFrom((comm.pose.Pose.Data) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(comm.pose.Pose.Data other) {
				if (other == comm.pose.Pose.Data.getDefaultInstance())
					return this;
				if (other.hasCommand()) {
					setCommand(other.getCommand());
				}
				if (other.hasStatus()) {
					setStatus(other.getStatus());
				}
				if (other.hasPose()) {
					mergePose(other.getPose());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (hasPose()) {
					if (!getPose().isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						int rawValue = input.readEnum();
						comm.pose.Pose.Data.Command value = comm.pose.Pose.Data.Command
								.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(1, rawValue);
						} else {
							bitField0_ |= 0x00000001;
							command_ = value;
						}
						break;
					}
					case 16: {
						int rawValue = input.readEnum();
						comm.pose.Pose.Data.Status value = comm.pose.Pose.Data.Status
								.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(2, rawValue);
						} else {
							bitField0_ |= 0x00000002;
							status_ = value;
						}
						break;
					}
					case 26: {
						comm.pose.Pose.PoseData.Builder subBuilder = comm.pose.Pose.PoseData
								.newBuilder();
						if (hasPose()) {
							subBuilder.mergeFrom(getPose());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setPose(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// optional .comm.pose.Data.Command command = 1;
			private comm.pose.Pose.Data.Command command_ = comm.pose.Pose.Data.Command.CARIBRATE;

			public boolean hasCommand() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public comm.pose.Pose.Data.Command getCommand() {
				return command_;
			}

			public Builder setCommand(comm.pose.Pose.Data.Command value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				command_ = value;
				onChanged();
				return this;
			}

			public Builder clearCommand() {
				bitField0_ = (bitField0_ & ~0x00000001);
				command_ = comm.pose.Pose.Data.Command.CARIBRATE;
				onChanged();
				return this;
			}

			// optional .comm.pose.Data.Status status = 2;
			private comm.pose.Pose.Data.Status status_ = comm.pose.Pose.Data.Status.ACK;

			public boolean hasStatus() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public comm.pose.Pose.Data.Status getStatus() {
				return status_;
			}

			public Builder setStatus(comm.pose.Pose.Data.Status value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				status_ = value;
				onChanged();
				return this;
			}

			public Builder clearStatus() {
				bitField0_ = (bitField0_ & ~0x00000002);
				status_ = comm.pose.Pose.Data.Status.ACK;
				onChanged();
				return this;
			}

			// optional .comm.pose.PoseData pose = 3;
			private comm.pose.Pose.PoseData pose_ = comm.pose.Pose.PoseData
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<comm.pose.Pose.PoseData, comm.pose.Pose.PoseData.Builder, comm.pose.Pose.PoseDataOrBuilder> poseBuilder_;

			public boolean hasPose() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public comm.pose.Pose.PoseData getPose() {
				if (poseBuilder_ == null) {
					return pose_;
				} else {
					return poseBuilder_.getMessage();
				}
			}

			public Builder setPose(comm.pose.Pose.PoseData value) {
				if (poseBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					pose_ = value;
					onChanged();
				} else {
					poseBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			public Builder setPose(
					comm.pose.Pose.PoseData.Builder builderForValue) {
				if (poseBuilder_ == null) {
					pose_ = builderForValue.build();
					onChanged();
				} else {
					poseBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			public Builder mergePose(comm.pose.Pose.PoseData value) {
				if (poseBuilder_ == null) {
					if (((bitField0_ & 0x00000004) == 0x00000004)
							&& pose_ != comm.pose.Pose.PoseData
									.getDefaultInstance()) {
						pose_ = comm.pose.Pose.PoseData.newBuilder(pose_)
								.mergeFrom(value).buildPartial();
					} else {
						pose_ = value;
					}
					onChanged();
				} else {
					poseBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			public Builder clearPose() {
				if (poseBuilder_ == null) {
					pose_ = comm.pose.Pose.PoseData.getDefaultInstance();
					onChanged();
				} else {
					poseBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public comm.pose.Pose.PoseData.Builder getPoseBuilder() {
				bitField0_ |= 0x00000004;
				onChanged();
				return getPoseFieldBuilder().getBuilder();
			}

			public comm.pose.Pose.PoseDataOrBuilder getPoseOrBuilder() {
				if (poseBuilder_ != null) {
					return poseBuilder_.getMessageOrBuilder();
				} else {
					return pose_;
				}
			}

			private com.google.protobuf.SingleFieldBuilder<comm.pose.Pose.PoseData, comm.pose.Pose.PoseData.Builder, comm.pose.Pose.PoseDataOrBuilder> getPoseFieldBuilder() {
				if (poseBuilder_ == null) {
					poseBuilder_ = new com.google.protobuf.SingleFieldBuilder<comm.pose.Pose.PoseData, comm.pose.Pose.PoseData.Builder, comm.pose.Pose.PoseDataOrBuilder>(
							pose_, getParentForChildren(), isClean());
					pose_ = null;
				}
				return poseBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:comm.pose.Data)
		}

		static {
			defaultInstance = new Data(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:comm.pose.Data)
	}

	public interface PoseDataOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int32 id = 1;
		boolean hasId();

		int getId();
	}

	public static final class PoseData extends
			com.google.protobuf.GeneratedMessage implements PoseDataOrBuilder {
		// Use PoseData.newBuilder() to construct.
		private PoseData(Builder builder) {
			super(builder);
		}

		private PoseData(boolean noInit) {
		}

		private static final PoseData defaultInstance;

		public static PoseData getDefaultInstance() {
			return defaultInstance;
		}

		public PoseData getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return comm.pose.Pose.internal_static_comm_pose_PoseData_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return comm.pose.Pose.internal_static_comm_pose_PoseData_fieldAccessorTable;
		}

		private int bitField0_;
		// required int32 id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public int getId() {
			return id_;
		}

		private void initFields() {
			id_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, id_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, id_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static comm.pose.Pose.PoseData parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static comm.pose.Pose.PoseData parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.PoseData parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static comm.pose.Pose.PoseData parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.PoseData parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static comm.pose.Pose.PoseData parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static comm.pose.Pose.PoseData parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static comm.pose.Pose.PoseData parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static comm.pose.Pose.PoseData parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static comm.pose.Pose.PoseData parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(comm.pose.Pose.PoseData prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				comm.pose.Pose.PoseDataOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return comm.pose.Pose.internal_static_comm_pose_PoseData_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return comm.pose.Pose.internal_static_comm_pose_PoseData_fieldAccessorTable;
			}

			// Construct using comm.pose.Pose.PoseData.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return comm.pose.Pose.PoseData.getDescriptor();
			}

			public comm.pose.Pose.PoseData getDefaultInstanceForType() {
				return comm.pose.Pose.PoseData.getDefaultInstance();
			}

			public comm.pose.Pose.PoseData build() {
				comm.pose.Pose.PoseData result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private comm.pose.Pose.PoseData buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				comm.pose.Pose.PoseData result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public comm.pose.Pose.PoseData buildPartial() {
				comm.pose.Pose.PoseData result = new comm.pose.Pose.PoseData(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof comm.pose.Pose.PoseData) {
					return mergeFrom((comm.pose.Pose.PoseData) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(comm.pose.Pose.PoseData other) {
				if (other == comm.pose.Pose.PoseData.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt32();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int32 id = 1;
			private int id_;

			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public int getId() {
				return id_;
			}

			public Builder setId(int value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:comm.pose.PoseData)
		}

		static {
			defaultInstance = new PoseData(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:comm.pose.PoseData)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_comm_pose_Message_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_comm_pose_Message_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_comm_pose_Data_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_comm_pose_Data_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_comm_pose_PoseData_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_comm_pose_PoseData_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\npose.proto\022\tcomm.pose\"n\n\007Message\022%\n\004ty"
				+ "pe\030\002 \002(\0162\027.comm.pose.Message.Type\022\035\n\004dat"
				+ "a\030\003 \002(\0132\017.comm.pose.Data\"\035\n\004Type\022\013\n\007COMM"
				+ "AND\020\001\022\010\n\004DATA\020\002\"\332\001\n\004Data\022(\n\007command\030\001 \001("
				+ "\0162\027.comm.pose.Data.Command\022&\n\006status\030\002 \001"
				+ "(\0162\026.comm.pose.Data.Status\022!\n\004pose\030\003 \001(\013"
				+ "2\023.comm.pose.PoseData\"\'\n\007Command\022\r\n\tCARI"
				+ "BRATE\020\001\022\r\n\tSEND_DATA\020\002\"4\n\006Status\022\007\n\003ACK\020"
				+ "\001\022\016\n\nCARIBRATED\020\002\022\021\n\rCAPTURED_POSE\020\003\"\026\n\010"
				+ "PoseData\022\n\n\002id\030\001 \002(\005" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_comm_pose_Message_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_comm_pose_Message_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_comm_pose_Message_descriptor,
						new java.lang.String[] { "Type", "Data", },
						comm.pose.Pose.Message.class,
						comm.pose.Pose.Message.Builder.class);
				internal_static_comm_pose_Data_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_comm_pose_Data_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_comm_pose_Data_descriptor,
						new java.lang.String[] { "Command", "Status", "Pose", },
						comm.pose.Pose.Data.class,
						comm.pose.Pose.Data.Builder.class);
				internal_static_comm_pose_PoseData_descriptor = getDescriptor()
						.getMessageTypes().get(2);
				internal_static_comm_pose_PoseData_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_comm_pose_PoseData_descriptor,
						new java.lang.String[] { "Id", },
						comm.pose.Pose.PoseData.class,
						comm.pose.Pose.PoseData.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
